In [15]:
# finding the max number

import pandas as pd
import numpy as np
import timeit

start = timeit.default_timer()

A = [1,7,3,4,11,2,6,9,8,10]
max = 0
for i in range(len(A)):
    if A[i] > max :
        max = A[i]
        
print(max)
stop = timeit.default_timer()
print('Time: ', stop - start)

11
Time:  0.0005607000000509288


In [16]:
start = timeit.default_timer()

A = [1,7,3,4,11,2,6,9,8,10]
A.sort()
        
print(A[-1])
stop = timeit.default_timer()
print('Time: ', stop - start)

11
Time:  0.00044000000002597517


In [33]:
arr = np.array([1,2,3,4,5])

In [34]:
arr

array([1, 2, 3, 4, 5])

In [35]:
print(arr)

[1 2 3 4 5]


In [37]:
a = [1,2,3,4,5]

In [38]:
arr = np.array(a)

In [44]:
#indexing 

arr[0],arr[4]

(1, 5)

In [189]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])

In [190]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
arr2[0,1]

2

In [48]:
arr2[1,0]

5

In [49]:
arr2[1,-1] 

8

In [50]:
arr2[0,-1]

4

In [53]:
arr2[-1,-1]

8

In [55]:
arr2[-2,-2]

3

In [57]:
arr2.ndim

2

In [58]:
arr.ndim

1

In [59]:
arr2[1:]

array([[5, 6, 7, 8]])

In [60]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [61]:
arr2[1,1:]

array([6, 7, 8])

In [63]:
arr2[0,1:3]

array([2, 3])

In [67]:
arr2[0:2:3]

array([[1, 2, 3, 4]])

In [69]:
arr2[::3]

array([[1, 2, 3, 4]])

In [70]:
arr2[1,1:3]

array([6, 7])

In [71]:
#data types

In [72]:
arr2.dtype

dtype('int32')

In [76]:
arr3 = np.array(['pen','banana','apple'])

In [77]:
arr3.dtype

dtype('<U6')

In [78]:
arr4 = np.array([1,'apple',2,'cat'])

In [80]:
arr4.dtype

dtype('<U11')

In [99]:
arr5 = np.array([1.1,2.2,3.3])

In [100]:
arr5.dtype

dtype('float64')

In [101]:
arr5 = arr5.astype('i')

In [102]:
arr5.dtype

dtype('int32')

In [103]:
arr5

array([1, 2, 3], dtype=int32)

In [104]:
#view or copy

x = arr5.view()
x

array([1, 2, 3], dtype=int32)

In [105]:
arr5[0] = 44

In [106]:
x

array([44,  2,  3], dtype=int32)

In [107]:
y = arr5.copy()
y

array([44,  2,  3], dtype=int32)

In [108]:
arr5[2] = 234

In [109]:
print(x)

[ 44   2 234]


In [110]:
print(y)

[44  2  3]


In [111]:
x.base

array([ 44,   2, 234], dtype=int32)

In [113]:
print(y.base)

None


In [114]:
arr5.shape

(3,)

In [115]:
arr2.shape

(2, 4)

In [125]:
arr = np.array([1,2,3,4,5,6])

In [126]:
arr.shape

(6,)

In [127]:
newarr = arr.reshape(2,3)

In [128]:
newarr

array([[1, 2, 3],
       [4, 5, 6]])

In [139]:
newarr = arr.reshape(3,2)
newarr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [132]:
newarr = newarr.reshape(-1)

In [140]:
newarr.shape

(3, 2)

In [136]:
np.transpose(newarr)

array([[1, 3, 5],
       [2, 4, 6]])

In [141]:
newarr.flatten()

array([1, 2, 3, 4, 5, 6])

In [142]:
arr6 = np.array([1,2,3,4])
arr7 = np.array([5,6,7,8])

In [144]:
np.concatenate((arr6,arr7))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [146]:
arr6one = np.array([[1,2,3],[4,5,6]])
arr7two = np.array([[4,5,6],[7,8,9]])

In [150]:
arrnew=np.concatenate((arr6one,arr7two),axis=1)
arrnew

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])

In [151]:
arrnew=np.concatenate((arr6one,arr7two),axis=0)
arrnew

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [7, 8, 9]])

In [168]:
arr = np.array([4,5,2,3,1,7,94,2,4,2])

In [169]:
np.sort(arr)

array([ 1,  2,  2,  2,  3,  4,  4,  5,  7, 94])

In [170]:
arr

array([ 4,  5,  2,  3,  1,  7, 94,  2,  4,  2])

In [175]:
arr2 = np.array([[8,6,7],[3,5,1]])

In [177]:
#sorted

np.sort(arr2)

array([[6, 7, 8],
       [1, 3, 5]])

In [180]:
arr2

array([[8, 6, 7],
       [3, 5, 1]])

In [178]:
for i in arr2:
    print(i)

[8 6 7]
[3 5 1]


In [181]:
arr

array([ 4,  5,  2,  3,  1,  7, 94,  2,  4,  2])

In [179]:
for i in arr:
    print(i)

4
5
2
3
1
7
94
2
4
2


In [182]:
for i in arr2:
    for j in i:
        print(j)

8
6
7
3
5
1


In [183]:
for i in np.nditer(arr2):
    print(i)

8
6
7
3
5
1


In [185]:
for i in np.nditer(arr4):
    print(i)

1
apple
2
cat


In [193]:
arr = arr2.reshape(-1)

In [199]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [200]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [209]:
r=np.where(arr2%2==0)

In [210]:
r

(array([0, 0, 1, 1], dtype=int64), array([1, 3, 1, 3], dtype=int64))

In [212]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [215]:
x=np.searchsorted(arr,7)
x

6

In [216]:
x=np.searchsorted(arr,700)
x

8

In [217]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [219]:
x=np.searchsorted(arr,[5,1])
x

array([4, 0], dtype=int64)

In [220]:
arrk = np.array([1,3,2,1,2,5,32,53,21,67])

In [229]:
u = np.searchsorted(arrk,21)
u

6

In [223]:
arrk

array([ 1,  3,  2,  1,  2,  5, 32, 53, 21, 67])

In [227]:
j =np.sort(arrk)
print(j)

[ 1  1  2  2  3  5 21 32 53 67]


In [236]:
arrb = [True,False,True,False]

In [237]:
arrb = np.array(arrb)

In [245]:
arr = np.array([11,12,33,44])

In [246]:
arrb

array([ True, False,  True, False])

In [247]:
new=arr[arrb]
new

array([11, 33])

In [267]:
arre = np.array([1,2,3,4,5,6,7,7,8,9,10])

In [268]:
filter = []
for ele in arre:
    if ele%2==0:
        filter.append(ele)

In [269]:
filter

[2, 4, 6, 8, 10]

In [270]:
filterb = []
for ele in arre:
    if ele%2==0:
        filterb.append(True)
    else:
        filterb.append(False)

In [271]:
filterb

[False, True, False, True, False, True, False, False, True, False, True]

In [272]:
np.mean(arre)

5.636363636363637

In [273]:
np.median(np.sort(arre))

6.0

In [274]:
from scipy import stats
stats.mode(arre)

ModeResult(mode=array([7]), count=array([2]))

In [275]:
np.std(arre)

2.7723546694503467

In [279]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [278]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [284]:
np.linspace(1,25,5)

array([ 1.,  7., 13., 19., 25.])

In [286]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [287]:
np.zeros(2)

array([0., 0.])

In [288]:
np.zeros(4)

array([0., 0., 0., 0.])

In [292]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [293]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [297]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [295]:
np.ones((1,4))

array([[1., 1., 1., 1.]])

In [296]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [298]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [308]:
np.random.rand()

0.04801281799240775

In [306]:
np.random.rand(2,2)

array([[0.95674306, 0.72767088],
       [0.42433568, 0.22716586]])

In [309]:
np.random.rand(5)

array([0.24812677, 0.70308179, 0.69673713, 0.57333587, 0.69009441])

In [318]:
np.random.randint(-10,-1)

-3

In [319]:
np.random.rand(6)

array([0.80039446, 0.38758638, 0.37929477, 0.61729226, 0.62480376,
       0.35210069])

In [320]:
np.sort(np.random.rand(6))

array([0.15191765, 0.23981458, 0.2508881 , 0.43849962, 0.60515932,
       0.88723727])

In [324]:
np.random.randint(2,8,(2,3))

array([[7, 6, 2],
       [3, 3, 7]])

In [349]:
randele = np.sort(np.random.randint(1,10000,size=1000))
randele

array([   6,   13,   26,   28,   29,   32,   33,   34,   51,   75,   78,
        111,  119,  122,  129,  143,  151,  164,  183,  185,  203,  212,
        215,  237,  242,  245,  257,  260,  261,  263,  298,  301,  302,
        313,  351,  360,  364,  368,  382,  384,  388,  418,  434,  462,
        463,  476,  482,  483,  490,  501,  501,  509,  521,  527,  532,
        538,  539,  546,  547,  547,  549,  565,  568,  570,  571,  578,
        579,  581,  583,  591,  610,  616,  617,  623,  637,  656,  675,
        683,  697,  716,  717,  732,  737,  744,  747,  755,  785,  791,
        806,  816,  821,  849,  874,  899,  899,  905,  911,  922,  923,
        928,  944,  974,  986, 1007, 1008, 1014, 1027, 1035, 1078, 1083,
       1090, 1099, 1102, 1102, 1117, 1123, 1124, 1152, 1157, 1165, 1166,
       1168, 1189, 1200, 1204, 1206, 1211, 1223, 1226, 1234, 1255, 1263,
       1273, 1277, 1284, 1287, 1288, 1324, 1325, 1326, 1353, 1354, 1368,
       1374, 1376, 1376, 1377, 1404, 1406, 1418, 14

In [332]:
arre

array([ 1,  2,  3,  4,  5,  6,  7,  7,  8,  9, 10])

In [350]:
np.min(randele)

6

In [351]:
np.max(randele)

9987

In [352]:
np.mean(randele)

4867.085

In [353]:
np.median(randele)

4836.0

In [354]:
np.std(randele)

2902.0626753698825

In [355]:
from scipy import stats

stats.mode(randele)

ModeResult(mode=array([8933]), count=array([3]))

In [377]:
arre

array([ 1,  6,  2,  3,  4,  7,  7, 10,  9,  5,  8])

In [376]:
#shuffle
x = np.random.shuffle(arre)
arre

array([ 1,  6,  2,  3,  4,  7,  7, 10,  9,  5,  8])

In [378]:
arr

array([44, 11, 12, 33])

In [381]:
#shuffle using permutation

np.random.permutation(arr)

array([12, 11, 44, 33])

In [382]:
arr

array([44, 11, 12, 33])